using System.Collections.Generic;

namespace BlueCloudK.WpfMusicTilesAI.Models
{
    /// <summary>
    /// Metadata about the generated song/beat map
    /// </summary>
    public class BeatMapMetadata
    {
        /// <summary>
        /// Creative title for the generated song
        /// </summary>
        public string Title { get; set; } = string.Empty;

        /// <summary>
        /// Total duration of the song in seconds (30-180)
        /// </summary>
        public double Duration { get; set; }

        /// <summary>
        /// Beats per minute (80-180)
        /// </summary>
        public int Bpm { get; set; }
    }

    /// <summary>
    /// Complete beat map generated by AI
    /// </summary>
    public class BeatMap
    {
        /// <summary>
        /// Metadata about the song
        /// </summary>
        public BeatMapMetadata Metadata { get; set; } = new();

        /// <summary>
        /// List of all notes in the beat map
        /// </summary>
        public List<Note> Notes { get; set; } = new();
    }
}
